# Default values for my-apps
global:
  imageRegistry: "dockerhub.kubekey.local"  # 统一的镜像仓库
  labels:
    app: my-apps
  annotations:
    example.com/note: "This is an example annotation"

apps:
  - name: app1
    image: app1
    tag: latest
    command: ["app1", "run"]
  - name: app2
    image: app2
    tag: v1.0.0
    # command 留空或不定义，表示不设置命令